# Ayaki General
robot_version: 5.0.1

# Ayaki Source
ayaki_logo_url: http://nas.hakubill.tech:1234/images/2022/02/27/Ayaki-Watermark.png
# è¡¨æƒ…åŒ…URL
liuhantangtang_url: http://image.hakubill.tech:1234/images/2022/07/04/IMG_2641.jpg
liuhantutu_url: http://image.hakubill.tech:1234/images/2022/07/04/IMG_2642.jpg
baochaoaoao_url: http://image.hakubill.tech:1234/images/2022/07/04/IMG_2643.jpg
# è€å©†åˆ—è¡¨
waifu_list:
  - name: è°·æ’æ¡é‡
    url: http://image.hakubill.tech:1234/images/2022/07/20/Guhengtaiye.jpg
    origin: å®…ç”·çš„äººé—´å†’é™© (Game, CN)
  - name: é›ªå¹³ä¸€æœ
    url: http://image.hakubill.tech:1234/images/2022/07/20/itsuka.png
    origin: ç›¸åˆä¹‹ç‰© (Anime, JP)
  - name: å¹³æ³½å”¯
    url: http://image.hakubill.tech:1234/images/2022/07/20/yui.png
    origin: è½»éŸ³å°‘å¥³ (Anime, JP)
  - name: ç™½æ²³è¤
    url: http://image.hakubill.tech:1234/images/2022/07/20/hotaru.png
    origin: Memories Off 2nd (Game, JP)
  - name: è€å©†
    url: http://image.hakubill.tech:1234/images/2022/07/20/Laopo.jpg
    origin: å®…ç”·çš„äººé—´å†’é™© (Game, CN)
  - name: ç´å¹äŒ·
    url: http://image.hakubill.tech:1234/images/2022/07/20/tsumugi.png
    origin: è½»éŸ³å°‘å¥³ (Anime, JP)
  - name: ä¸­é‡æ¢“
    url: http://image.hakubill.tech:1234/images/2022/07/20/azusa.png
    origin: è½»éŸ³å°‘å¥³ (Anime, JP)
  - name: å‡‰å®«æ˜¥æ—¥
    url: http://image.hakubill.tech:1234/images/2022/07/20/haruhi.png
    origin: å‡‰å®«æ˜¥æ—¥çš„å¿§éƒ (Anime/Novel, JP)
  - name: è—¤åŸåƒèŠ±
    url: http://image.hakubill.tech:1234/images/2022/07/20/fujihara.png
    origin: è¾‰å¤œå¤§å°å§æƒ³è®©æˆ‘å‘Šç™½ (Anime/Comic, JP)
  - name: é«˜æœ¨
    url: http://image.hakubill.tech:1234/images/2022/07/20/takagi.jpg
    origin: æ“…é•¿æ‰å¼„çš„é«˜æœ¨åŒå­¦ (Anime/Comic, JP)
  - name: èŠ±å‚ç»“è¡£
    url: http://image.hakubill.tech:1234/images/2022/07/20/hanasaka_yui.png
    origin: One Room (Anime, JP)
  - name: æ¡ƒåŸå¥ˆæœˆ
    url: http://image.hakubill.tech:1234/images/2022/07/20/momohara_natsuki.png
    origin: One Room (Anime, JP)

# éŸ³ä¹åˆ—è¡¨ï¼ˆæš‚æ—¶æ— ç”¨ï¼‰
music_list:
  - name: ãƒãƒ«ãƒãƒ’
  - artist: Tsubaki
  - url: http://zhuaiyuwen.xyz/share/harunohi.mp3

# Ayaki features
# è¿åŠ¿åˆ—è¡¨
unsei_list:
  - â˜…â˜…â˜…å¤§å‰â˜…â˜…â˜…
  - â˜…â˜…ä¸­å‰â˜…â˜…
  - â˜…å°å‰â˜…
  - å‰
  - æœ«å‰
  - å‡¶
  - å¤§å‡¶

# å®œå¿Œäº‹ä»¶åˆ—è¡¨
event_list:
  - æ‘†çƒ‚
  - å®…å®¶
  - ç‚¹å¤–å–
  - ğŸ¤º
  - æ¶©æ¶©
  - dd
  - çœ‹è€å©†
  - ç¡è§‰
  - æ‰“æ’¸
  - çœ‹å›¾
  - çœ‹ç‰‡
  - å†™æ–‡
  - ğŸ¦
  - æŠ½å¡
  - è¿½ç•ª
  - è¡¥ç•ª
  - å¹²é¥­
  - å–å¼±
  - ä¼ æ’­ç„¦è™‘
  - æ“ç‚‰
  - å¼€äº‘
  - çˆ†ç‚’ğŸ¬ğŸ¬
  - æµæ±—ç³–è±†
  - ğŸ˜‹
  - ğŸ˜°
  - ç†å‘åº—
  - ä¸‹æ£‹
  - æ°´ç¾¤
  - è¹­é¥­
  - çœ‹ä¹¦
  - é˜´é˜³æ€ªæ°”
  - çˆ†ç‚’åœŸåœŸ
  - æµæ±—åœŸè±†
  - æ¡¥æ´åº•ä¸‹ç›–å°è¢«
  - ç¿˜è¯¾
  - çˆ†ç‚’å¥¥å¥¥
  - ğŸ˜…
  - ğŸ¥µ
